### ISSUE TITLE
[storage]: enable `BUF` linter and compiler

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#329]
see https://buf.build/docs/lint/usage#5.-docker

and https://github.com/opiproject/opi-api/commit/0729d7f3a61269ac846f8dff8872ad4bcd9ed30e :
```
jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
```
